name: Ejercicio3

on:
  push:
    branches: ["main"]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 14
      - run: npm install
      - run: npm pack
      - run: ls
      - uses: actions/upload-artifact@v2
        with:
          name: npm-package
          path: https://npm.pkg.github.com
      
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
